### ISSUE TITLE
Make it so after recently turning on a device it checks for when it has finished booting, so it can log the up-time more accurately.

### ISSUE THREAD

**Issue by Matthew-Kasper** [Matthew-Kasper/WakeOnLANForwarder#10]

**Comment by arniber21** [comment]
Idea for this - have a microservice built that runs on the server, listening for a ping request with a specific signature. That signature is sent by the Pico W. When that microservice responds, the Pico W knows that it is up. To implement this, we need to build another microservice that runs on the server. This is also compatible with implementing the kill function.

**Comment by Matthew-Kasper** [comment]
Simply made the pico ping the server every 60 seconds to check if it should start an up-timer. We already have functionality to accurately check uptime based on a saved start time.
